
# Credits https://gist.github.com/thatisuday/b3b6096457e64cdfa20796315ed29fbd

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-linux:
    name: Build the application in Linux environment
    runs-on: ubuntu-latest
    steps:
      
      # step 1: set up go
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      
      # step 2: checkout repository code
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2

      # step 3: install dependencies
      - name: Install all Go dependencies
        run: go get
      
      # step 4: run the application
      - name: go run
        run: go run ./main.go -l 30