# Template from https://github.com/BenjaminNavarro/docker-manager/blob/master/.github/workflows/release.yml

on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel for different OSs and architectures 
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
        exclude:  
          - goarch: "386"
            goos: darwin 
          - goarch: arm64
            goos: windows 
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@latest
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        extra_files: LICENSE README.md
        md5sum: False
        sha256sum: True
        goversion: latest
